### ISSUE TITLE
Maintennance/Complaints

### ISSUE THREAD

**Issue by aftershade-guest** [ComplexPeople/complex-people#11]
### **Tasks**

- [x] Tickets should be modifiable (change status)
- [x] Endpoints for making complaints/ maintenance tickets.
- [x] Maintenance issues should be assigned to staff members

### **POSSIBLE ENDPOINTS**

- Get all tickets (ordered by date) 
- Get specific tickets (either by apartment id or people id) ordered by date then by status
- Get specific ticket (by ticket id)
- Post/Create a new ticket
- Modify/update ticket status
-
- Get tickets by status (Maybe) (but can also be done by filtering response from all tickets)
